;; theme file, written [insert date here]
;; created by GimpMill -- DO NOT EDIT!

(require 'make-theme)

(let
	(
		(patterns-alist
		 '(
				("title" ;; 83 x 19
					(inactive "title.png")
					(focused "title.png")
					(highlighted "title.png")
					(clicked "title.png")
				)
				("t" ;; 102 x 4
					(inactive "t.png")
					(focused "t.png")
					(highlighted "t.png")
					(clicked "t.png")
				)
				("tr" ;; 23 x 23
					(inactive "tr.png")
					(focused "tr.png")
					(highlighted "tr.png")
					(clicked "tr.png")
				)
				("max" ;; 19 x 19
					(inactive "max.png")
					(focused "max.png")
					(highlighted "max.png")
					(clicked "max.png")
				)
				("min" ;; 19 x 19
					(inactive "min.png")
					(focused "min.png")
					(highlighted "min.png")
					(clicked "min.png")
				)
				("tl" ;; 23 x 23
					(inactive "tl.png")
					(focused "tl.png")
					(highlighted "tl.png")
					(clicked "tl.png")
				)
				("menu" ;; 19 x 19
					(inactive "menu.png")
					(focused "menu.png")
					(highlighted "menu.png")
					(clicked "menu.png")
				)
				("l" ;; 4 x 79
					(inactive "l.png")
					(focused "l.png")
					(highlighted "l.png")
					(clicked "l.png")
				)
				("bl" ;; 23 x 23
					(inactive "bl.png")
					(focused "bl.png")
					(highlighted "bl.png")
					(clicked "bl.png")
				)
				("br" ;; 23 x 23
					(inactive "br.png")
					(focused "br.png")
					(highlighted "br.png")
					(clicked "br.png")
				)
				("b" ;; 102 x 4
					(inactive "b.png")
					(focused "b.png")
					(highlighted "b.png")
					(clicked "b.png")
				)
				("r" ;; 4 x 79
					(inactive "r.png")
					(focused "r.png")
					(highlighted "r.png")
					(clicked "r.png")
				)
				("t-title" ;; 104 x 12
					(inactive "t-title.png")
					(focused "t-title.png")
					(highlighted "t-title.png")
					(clicked "t-title.png")
				)
				("t-tr" ;; 16 x 16
					(inactive "t-tr.png")
					(focused "t-tr.png")
					(highlighted "t-tr.png")
					(clicked "t-tr.png")
				)
				("t-max" ;; 12 x 12
					(inactive "t-max.png")
					(focused "t-max.png")
					(highlighted "t-max.png")
					(clicked "t-max.png")
				)
				("t-min" ;; 12 x 12
					(inactive "t-min.png")
					(focused "t-min.png")
					(highlighted "t-min.png")
					(clicked "t-min.png")
				)
				("t-tl" ;; 16 x 16
					(inactive "t-tl.png")
					(focused "t-tl.png")
					(highlighted "t-tl.png")
					(clicked "t-tl.png")
				)
				("t-menu" ;; 12 x 12
					(inactive "t-menu.png")
					(focused "t-menu.png")
					(highlighted "t-menu.png")
					(clicked "t-menu.png")
				)
				("t-t" ;; 116 x 4
					(inactive "t-t.png")
					(focused "t-t.png")
					(highlighted "t-t.png")
					(clicked "t-t.png")
				)
				("t-bl" ;; 16 x 16
					(inactive "t-bl.png")
					(focused "t-bl.png")
					(highlighted "t-bl.png")
					(clicked "t-bl.png")
				)
				("t-br" ;; 16 x 16
					(inactive "t-br.png")
					(focused "t-br.png")
					(highlighted "t-br.png")
					(clicked "t-br.png")
				)
				("t-b" ;; 116 x 4
					(inactive "t-b.png")
					(focused "t-b.png")
					(highlighted "t-b.png")
					(clicked "t-b.png")
				)
				("t-l" ;; 4 x 86
					(inactive "t-l.png")
					(focused "t-l.png")
					(highlighted "t-l.png")
					(clicked "t-l.png")
				)
				("t-r" ;; 4 x 86
					(inactive "t-r.png")
					(focused "t-r.png")
					(highlighted "t-r.png")
					(clicked "t-r.png")
				)

			)
		)
		(frames-alist
		 '(
				("normal"
					(
						(background . "title")
						(left-edge . 19)
						(right-edge . 38)
						(top-edge . -19)
						(class . title)
						(text . window-name)
						(x-justify . center)
						(y-justify . center)
						(foreground . "#FFFFFF")
					)
					(
						(background . "t")
						(left-edge . 19)
						(right-edge . 19)
						(top-edge . -23)
						(class . top-border)
					)
					(
						(background . "tr")
						(right-edge . -4)
						(top-edge . -23)
						(class . top-right-corner)
					)
					(
						(background . "max")
						(right-edge . 0)
						(top-edge . -19)
						(class . maximize-button)
					)
					(
						(background . "min")
						(right-edge . 19)
						(top-edge . -19)
						(class . iconify-button)
					)
					(
						(background . "tl")
						(left-edge . -4)
						(top-edge . -23)
						(class . top-left-corner)
					)
					(
						(background . "menu")
						(left-edge . 0)
						(top-edge . -19)
						(class . menu-button)
					)
					(
						(background . "l")
						(left-edge . -4)
						(top-edge . 0)
						(bottom-edge . 19)
						(class . left-border)
					)
					(
						(background . "bl")
						(left-edge . -4)
						(bottom-edge . -4)
						(class . bottom-left-corner)
					)
					(
						(background . "br")
						(right-edge . -4)
						(bottom-edge . -4)
						(class . bottom-right-corner)
					)
					(
						(background . "b")
						(left-edge . 19)
						(right-edge . 19)
						(bottom-edge . -4)
						(class . bottom-border)
					)
					(
						(background . "r")
						(right-edge . -4)
						(top-edge . 0)
						(bottom-edge . 19)
						(class . title)
					)
				)				("shaped"
					(
						(background . "title")
						(left-edge . 19)
						(right-edge . 38)
						(top-edge . -19)
						(class . title)
						(text . window-name)
						(x-justify . center)
						(y-justify . center)
						(foreground . "#FFFFFF")
					)
					(
						(background . "t")
						(left-edge . 19)
						(right-edge . 19)
						(top-edge . -23)
						(class . top-border)
					)
					(
						(background . "tr")
						(right-edge . -4)
						(top-edge . -23)
						(class . top-right-corner)
					)
					(
						(background . "max")
						(right-edge . 0)
						(top-edge . -19)
						(class . maximize-button)
					)
					(
						(background . "min")
						(right-edge . 19)
						(top-edge . -19)
						(class . iconify-button)
					)
					(
						(background . "tl")
						(left-edge . -4)
						(top-edge . -23)
						(class . top-left-corner)
					)
					(
						(background . "menu")
						(left-edge . 0)
						(top-edge . -19)
						(class . menu-button)
					)
				)				("transient"
					(
						(background . "t-title")
						(left-edge . 12)
						(right-edge . 24)
						(top-edge . -12)
						(class . title)
					)
					(
						(background . "t-tr")
						(right-edge . -4)
						(top-edge . -16)
						(class . menu-button)
					)
					(
						(background . "t-max")
						(right-edge . 0)
						(top-edge . -12)
						(class . maximize-button)
					)
					(
						(background . "t-min")
						(right-edge . 12)
						(top-edge . -12)
						(class . iconify-button)
					)
					(
						(background . "t-tl")
						(left-edge . -4)
						(top-edge . -16)
						(class . top-left-corner)
					)
					(
						(background . "t-menu")
						(left-edge . 0)
						(top-edge . -12)
						(class . menu-button)
					)
					(
						(background . "t-t")
						(left-edge . 12)
						(right-edge . 12)
						(top-edge . -16)
						(class . top-border)
					)
					(
						(background . "t-bl")
						(left-edge . -4)
						(bottom-edge . -4)
						(class . bottom-left-corner)
					)
					(
						(background . "t-br")
						(right-edge . -4)
						(bottom-edge . -4)
						(class . bottom-right-corner)
					)
					(
						(background . "t-b")
						(left-edge . 12)
						(right-edge . 12)
						(bottom-edge . -4)
						(class . bottom-border)
					)
					(
						(background . "t-l")
						(left-edge . -4)
						(top-edge . 0)
						(bottom-edge . 12)
						(class . left-border)
					)
					(
						(background . "t-r")
						(right-edge . -4)
						(top-edge . 0)
						(bottom-edge . 12)
						(class . none)
					)
				)				("shaped-transient"
					(
						(background . "t-title")
						(left-edge . 12)
						(right-edge . 24)
						(top-edge . -12)
						(class . title)
					)
					(
						(background . "t-tr")
						(right-edge . -4)
						(top-edge . -16)
						(class . menu-button)
					)
					(
						(background . "t-max")
						(right-edge . 0)
						(top-edge . -12)
						(class . maximize-button)
					)
					(
						(background . "t-min")
						(right-edge . 12)
						(top-edge . -12)
						(class . iconify-button)
					)
					(
						(background . "t-tl")
						(left-edge . -4)
						(top-edge . -16)
						(class . top-left-corner)
					)
					(
						(background . "t-menu")
						(left-edge . 0)
						(top-edge . -12)
						(class . menu-button)
					)
					(
						(background . "t-t")
						(left-edge . 12)
						(right-edge . 12)
						(top-edge . -16)
						(class . top-border)
					)
				)				("unframed"
				)
			)
		)
		(mapping-alist
		 '(
				(default . "normal")
				(transient . "transient")
				(shaped . "shaped")
				(shaped-transient . "shaped-transient")
				(unframed . "nil")
			)
		)

		(theme-name 'Win31)
	)

	(add-frame-style theme-name 
		(make-theme patterns-alist frames-alist mapping-alist)
	)
	(when 
		(boundp 'mark-frame-style-editable)
		(mark-frame-style-editable theme-name)
	)
)
